language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jeirsen/docker-production -f Dockerfile.dev .

scripts:
  - docker run jeirsen/docker-production npm run test -- --coverage

notifications:
  email:
    - jeirsen@gmail.com

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-509267483014"
  bucket_path: "Docker"
  on:
    branch: master
